Setting up a script to install needed packages

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,66 +3,21 @@ virtualenv:
   system_site_packages: true
 env:
   matrix:
-    - PYTHON_VERSION="2.7"  PARALLEL="mpich2"
-    - PYTHON_VERSION="2.7"  PARALLEL="false"
-    - PYTHON_VERSION="2.6"  PARALLEL="false"
-install:
-  - sudo apt-get update
-  - sudo apt-get install gfortran
+    - PYTHON_VERSION="2.7"  PARALLEL="mpich2"  DISTRIB="conda"
+    - PYTHON_VERSION="2.7"  PARALLEL="false"   DISTRIB="conda"
+    - PYTHON_VERSION="2.6"  PARALLEL="false"   DISTRIB="conda"
 
-  - if [[ "$PARALLEL" == "mpich2" ]]; then
-       sudo apt-get install mpich2;
-       mpirun -np 4 pwd;
-    fi
+install: source tools/install.sh
 
-  # Deactivate the travis-provided virtual environment and setup a
-  # conda-based environment instead
-  - deactivate
-  - wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
-  - chmod +x miniconda.sh && ./miniconda.sh -b
-  - export PATH=/home/travis/miniconda/bin:$PATH
-  - conda config --set always_yes yes --set changeps1 no
-  - conda update -q conda
+script: python runtests.py
 
-  # Useful for debugging any issues with conda
-  - conda info -a
+after_success:
+    # Ignore coveralls failures as the coveralls server is not very reliable
+    # but we don't want travis to report a failure in the github UI just
+    # because the coverage report failed to be published.
+    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
 
-  # Conda dependencies
-  - conda create -n testenv --yes python=$PYTHON_VERSION pip numpy scipy netcdf4 nose matplotlib
-  - source activate testenv
-
-  - python --version
-
-  # Get GDAL from the PinguCarsti binstar channel for python 2.7 
-  # On osx get GDAL from jjhelmus binstar channel
-  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
-       conda install -c pingucarsti gdal;
-       export GDAL_DATA=`gdal-config --datadir`;
-    fi
-
-  - if [[ "$PYTHON_VERSION" == "2.6" ]]; then conda install gdal; fi
-
-  # Install more software to deal with geographical projections
-  - pip install pyproj
-
-  # python 2.6 doesn't have argparse by default
-  - if [[ "$PYTHON_VERSION" == "2.6" ]]; then conda install argparse; fi
+cache: apt
 
 
-  # Install pypar if parallel
-  - if [[ "$PARALLEL" == "mpich2" ]]; then
-       svn checkout http://pypar.googlecode.com/svn/ pypar;
-       cd pypar/source;
-       python setup.py install;
-       cd ../..;
-    fi
 
-  # More debugging
-  - printenv
-  - conda list
-
-  - python setup.py install
-
-script:
-  # Your test script goes here
-  - python runtests.py
