mimic travis setup

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -14,16 +14,19 @@ jobs:
       uses: actions/setup-python@v3
       with:
         python-version: '3.12'
+    - name: Deactivate the system python
+      run: |
+        deactivate || echo "deactivate failed"
     - name: Add conda to system path
       run: |
         # $CONDA is an environment variable pointing to the root of the miniconda directory
         echo $CONDA/bin >> $GITHUB_PATH
     - name: Install dependencies
       run: |
-        conda init
-        source /home/runner/.bashrc
-        conda env update --name base
-        conda env create -f environment.yml --name anuga_env
+        conda init bash
+        source ~/.bashrc
+        conda update --yes conda
+        conda env create -c conda-forge -f environment.yml --name anuga_env
         conda activate anuga_env
 
     - name: Build with pip (using meson)
